on: pull_request_target

name: Create issue on Jira

jobs:
  build:
    runs-on: ubuntu-latest
    name: Login and Create issue
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
       
    - name: Create Issue
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: FE
        issuetype: Task
        summary: |
         New PR: ${{ github.event.pull_request.title }} 
        description: |
          ${{ github.event.pull_request.url }}
